title: Matt Crook
baseURL: https://mattcrook.io
languageCode: en-NZ

enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true

paginate: 8
paginatePath: p
summaryLength: 10

menu:
  main:
    - name: journal
      url: /journal/
    - name: projects
      url: /projects/
  
  journal:
    - name: Index
      url: /journal/
      weight: 1
    - name: Archive
      url: /archives/journal/
      weight: 2

  footer:
    - name: GitHub
      url: https://github.com/crookm
    - name: Twitter
      url: https://twitter.com/mattlc_3

module:
  imports:
  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5