title: Matt Crook
languageCode: en-NZ
baseURL: https://mattcrook.io/

enableGitInfo: true
enableRobotsTXT: true
enableInlineShortcodes: true

paginate: 10
summaryLength: 10

permalinks:
  posts: "/posts/:year/:slug"

taxonomies:
  tag: tags
  category: categories
  series: series

markup:
  highlight:
    guessSyntax: false
    codeFences: true
    noClasses: true
    lineNos: true

menu:
  main:
    - name: posts
      url: /posts/
    - name: projects
      url: /projects/
  
  posts:
    - name: Index
      url: /posts/
      weight: 1
    - name: Archive
      url: /archives/posts/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3
    - name: Series
      url: /series/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5

  footer:
    - name: GitHub
      url: https://github.com/crookm
    - name: Mastodon
      url: https://mastodon.nz/@matt

module:
  imports:
  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
