title: Matt Crook
languageCode: en-NZ

enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
enableInlineShortcodes: true

paginate: 10
paginatePath: p
summaryLength: 10

uglyURLs: true
permalinks:
  posts: "/posts/:year/:slug"

taxonomies:
  tag: "tags"
  category: "categories"

markup:
  highlight:
    guessSyntax: false
    codeFences: true
    noClasses: true

menu:
  main:
    - name: posts
      url: /posts.html
    - name: projects
      url: /projects.html
  
  posts:
    - name: Index
      url: /posts.html
      weight: 1
    - name: Archive
      url: /archives/posts.html
      weight: 2

  footer:
    - name: GitHub
      url: https://github.com/crookm
    - name: Mastodon
      url: https://mastodon.nz/@matt

module:
  imports:
  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5