title: Matt Crook
languageCode: en-NZ
baseURL: https://mattcrook.nz/

uglyURLs: true
enableGitInfo: true
enableInlineShortcodes: true

pagination:
  pagerSize: 10
summaryLength: 10

permalinks:
  posts: "/posts/:year/:slug"

taxonomies:
  tag: tags
  category: categories
  series: series

markup:
  highlight:
    guessSyntax: false
    codeFences: true
    noClasses: true

privacy:
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: posts
      url: /posts.html
    - name: projects
      url: /projects.html
  
  posts:
    - name: Index
      url: /posts.html
      weight: 1
    - name: Archive
      url: /archives/posts.html
      weight: 2
    - name: Categories
      url: /categories.html
      weight: 3
    - name: Series
      url: /series.html
      weight: 4
    - name: Tags
      url: /tags.html
      weight: 5

  footer:
    - name: GitHub
      url: https://github.com/crookm
    - name: Mastodon
      url: https://mastodon.nz/@matt

module:
  imports:
  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
